"""
S7 — Automated DMCA / Takedown Notice Generator

Generates DMCA takedown notices based on scan results.
Supports multiple platforms (Google, social media, generic hosting).
Stores notices in Firestore for tracking status.
"""
import uuid
from datetime import datetime, timezone

PLATFORM_CONTACTS = {
    "google.com":      {"name": "Google", "email": "dmca-agent@google.com", "form": "https://support.google.com/legal/troubleshooter/1114905"},
    "youtube.com":     {"name": "YouTube", "email": "copyright@youtube.com", "form": "https://www.youtube.com/copyright_complaint_form"},
    "facebook.com":    {"name": "Facebook/Meta", "email": "ip@fb.com", "form": "https://www.facebook.com/help/contact/634636770043106"},
    "instagram.com":   {"name": "Instagram", "email": "ip@instagram.com", "form": "https://help.instagram.com/contact/552695131608132"},
    "twitter.com":     {"name": "X/Twitter", "email": "copyright@twitter.com", "form": "https://help.twitter.com/forms/dmca"},
    "x.com":           {"name": "X/Twitter", "email": "copyright@twitter.com", "form": "https://help.twitter.com/forms/dmca"},
    "tiktok.com":      {"name": "TikTok", "email": "copyright@tiktok.com", "form": "https://www.tiktok.com/legal/report/Copyright"},
    "reddit.com":      {"name": "Reddit", "email": "copyright@reddit.com", "form": "https://reddit.zendesk.com/hc/en-us/requests/new?ticket_form_id=106573"},
    "pinterest.com":   {"name": "Pinterest", "email": "copyright@pinterest.com", "form": "https://help.pinterest.com/en/contact/copyright"},
    "linkedin.com":    {"name": "LinkedIn", "email": "copyright@linkedin.com", "form": "https://www.linkedin.com/help/linkedin/ask/TS-NDBCP"},
}


def get_platform_info(domain: str) -> dict:
    for key, info in PLATFORM_CONTACTS.items():
        if domain.endswith(key):
            return info
    return {"name": domain, "email": f"abuse@{domain}", "form": ""}


def generate_dmca_notice(
    owner_name: str,
    owner_email: str,
    asset_name: str,
    asset_id: str,
    original_url: str,
    infringing_url: str,
    domain: str,
    confidence: float = 0,
    additional_info: str = "",
) -> dict:
    platform = get_platform_info(domain)
    dmca_id = f"DMCA-{uuid.uuid4().hex[:8].upper()}"
    now = datetime.now(timezone.utc)
    conf_pct = round(confidence * 100)

    notice_text = f"""DMCA TAKEDOWN NOTICE
Reference: {dmca_id}
Date: {now.strftime('%B %d, %Y')}

To: {platform['name']} Copyright Agent
Re: Copyright Infringement — Notification under 17 U.S.C. § 512(c)

Dear {platform['name']} Copyright Team,

I am writing to notify you of copyright infringement occurring on your platform, in accordance with the Digital Millennium Copyright Act (17 U.S.C. § 512).

IDENTIFICATION OF COPYRIGHTED WORK:
  Title/Description: {asset_name}
  Original URL: {original_url}
  Asset ID: {asset_id}
  Match Confidence: {conf_pct}%

INFRINGING MATERIAL:
  URL: {infringing_url}
  Platform: {platform['name']}
  Domain: {domain}

I have a good faith belief that the use of the copyrighted material described above is not authorized by the copyright owner, its agent, or the law.

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner or am authorized to act on behalf of the owner.

CONTACT INFORMATION:
  Name: {owner_name}
  Email: {owner_email}

This notice was generated by SportShield Content Protection Platform.
Detection method: Perceptual hash matching ({conf_pct}% confidence)
{f'Additional context: {additional_info}' if additional_info else ''}

Sincerely,
{owner_name}
"""

    return {
        "dmcaId": dmca_id,
        "noticeText": notice_text,
        "assetId": asset_id,
        "assetName": asset_name,
        "originalUrl": original_url,
        "infringingUrl": infringing_url,
        "domain": domain,
        "platform": platform,
        "confidence": confidence,
        "ownerName": owner_name,
        "ownerEmail": owner_email,
        "status": "draft",
        "createdAt": now,
    }


def generate_batch_notices(
    owner_name: str,
    owner_email: str,
    asset_name: str,
    asset_id: str,
    original_url: str,
    scan_results: list,
) -> list:
    notices = []
    for result in scan_results:
        if result.get("classification") == "authorized":
            continue
        url = result.get("foundUrl", result.get("found_url", ""))
        domain = result.get("domain", "")
        if not domain:
            try:
                from urllib.parse import urlparse
                domain = urlparse(url if "://" in url else f"https://{url}").hostname or ""
                domain = domain.replace("www.", "")
            except Exception:
                domain = ""
        if not url:
            continue

        notice = generate_dmca_notice(
            owner_name=owner_name,
            owner_email=owner_email,
            asset_name=asset_name,
            asset_id=asset_id,
            original_url=original_url,
            infringing_url=url,
            domain=domain,
            confidence=result.get("confidence", 0),
        )
        notices.append(notice)
    return notices
