const now = new Date();
const day = 86400000;

const ts = (daysAgo) => {
  const d = new Date(now.getTime() - daysAgo * day);
  return { toDate: () => d, seconds: Math.floor(d.getTime() / 1000) };
};

export const DEMO_ASSETS = [
  {
    id: 'demo-asset-1',
    filename: 'premier-league-arsenal-goal-highlights.mp4',
    type: 'video',
    status: 'complete',
    originalUrl: '/images/sportshield-logo-transparent.png',
    matchCount: 11,
    unauthorizedCount: 9,
    authorizedCount: 2,
    scanCount: 38,
    riskScore: 88,
    riskLabel: 'critical',
    uploadedAt: ts(5),
    aiDetection: { is_ai: false, confidence: 0.03 },
    deepfakeAnalysis: null,
  },
  {
    id: 'demo-asset-2',
    filename: 'la-liga-el-clasico-broadcast.mp4',
    type: 'video',
    status: 'complete',
    originalUrl: null,
    matchCount: 7,
    unauthorizedCount: 6,
    authorizedCount: 1,
    scanCount: 24,
    riskScore: 82,
    riskLabel: 'critical',
    uploadedAt: ts(3),
    aiDetection: { is_ai: false, confidence: 0.02 },
    deepfakeAnalysis: null,
  },
  {
    id: 'demo-asset-3',
    filename: 'nba-finals-lebron-dunk.jpg',
    type: 'image',
    status: 'complete',
    originalUrl: '/images/sportshield-logo-transparent.png',
    matchCount: 4,
    unauthorizedCount: 2,
    authorizedCount: 2,
    scanCount: 19,
    riskScore: 45,
    riskLabel: 'medium',
    uploadedAt: ts(12),
    aiDetection: { is_ai: false, confidence: 0.01 },
    deepfakeAnalysis: null,
  },
  {
    id: 'demo-asset-4',
    filename: 'champions-league-semifinal-penalty.mp4',
    type: 'video',
    status: 'scanning',
    originalUrl: '/images/sportshield-logo-transparent.png',
    matchCount: 0,
    unauthorizedCount: 0,
    authorizedCount: 0,
    scanCount: 1,
    riskScore: 0,
    riskLabel: 'low',
    uploadedAt: ts(0.5),
    aiDetection: null,
    deepfakeAnalysis: null,
  },
  {
    id: 'demo-asset-5',
    filename: 'wimbledon-final-match-point.jpg',
    type: 'image',
    status: 'complete',
    originalUrl: '/images/sportshield-logo-transparent.png',
    matchCount: 14,
    unauthorizedCount: 12,
    authorizedCount: 2,
    scanCount: 42,
    riskScore: 95,
    riskLabel: 'critical',
    uploadedAt: ts(21),
    aiDetection: { is_ai: true, confidence: 0.87 },
    deepfakeAnalysis: { isDeepfake: true, confidence: 0.81 },
  },
];

export const DEMO_ALERTS = [
  {
    id: 'demo-alert-1',
    assetId: 'demo-asset-5',
    userId: 'demo_user',
    confidence: 0.96,
    foundUrl: 'https://totalsportek.com/wimbledon-final-stream/',
    thumbnailUrl: null,
    severity: 'high',
    riskScore: 96,
    riskLabel: 'critical',
    classification: 'unauthorized',
    isRead: false,
    createdAt: ts(0.3),
    smartSummary: 'Critical unauthorized use detected on totalsportek.com — a known piracy hub. Match confidence is 96%, the asset is your Wimbledon match-point photo. No license exists and the domain has a history of DMCA violations. Automated takedown notice has been pre-generated.',
  },
  {
    id: 'demo-alert-2',
    assetId: 'demo-asset-1',
    confidence: 0.89,
    foundUrl: 'https://sportsurge.io/premier-league-replay-arsenal',
    thumbnailUrl: null,
    severity: 'high',
    riskScore: 87,
    riskLabel: 'critical',
    classification: 'unauthorized',
    isRead: false,
    createdAt: ts(0.8),
    smartSummary: 'High-confidence unauthorized redistribution on sportsurge.io. Your Arsenal goal highlights video is being streamed without authorization. Confidence is 89%, risk score 87. This platform is a repeat offender — DMCA escalation recommended.',
  },
  {
    id: 'demo-alert-3',
    assetId: 'demo-asset-2',
    confidence: 0.92,
    foundUrl: 'https://buffstreams.tv/la-liga-el-clasico-live',
    thumbnailUrl: null,
    severity: 'high',
    riskScore: 91,
    riskLabel: 'critical',
    classification: 'unauthorized',
    isRead: false,
    createdAt: ts(1.5),
    smartSummary: 'Critical piracy detected on buffstreams.tv. Your El Clasico broadcast is being redistributed live with 92% confidence match. The platform serves over 2M monthly visitors. DMCA takedown and ISP-level escalation recommended.',
  },
  {
    id: 'demo-alert-4',
    assetId: 'demo-asset-3',
    confidence: 0.71,
    foundUrl: 'https://reddit.com/r/nbastreams/comments/highlights-lebron',
    thumbnailUrl: null,
    severity: 'medium',
    riskScore: 48,
    riskLabel: 'medium',
    classification: 'unauthorized',
    isRead: false,
    createdAt: ts(3),
    smartSummary: 'Medium-risk use on Reddit. Your NBA Finals photo is being shared in r/nbastreams. Match confidence is 71%. This may fall under fan sharing but the subreddit has a history of piracy links. Consider DMCA notice to Reddit.',
  },
  {
    id: 'demo-alert-5',
    assetId: 'demo-asset-1',
    confidence: 0.58,
    foundUrl: 'https://footybite.cc/arsenal-goals-free-download',
    thumbnailUrl: null,
    severity: 'medium',
    riskScore: 42,
    riskLabel: 'medium',
    classification: 'unauthorized',
    isRead: true,
    createdAt: ts(4),
    smartSummary: 'Moderate-risk detection on footybite.cc. Your Arsenal highlights are offered as a free download. Confidence is 58% due to compression artifacts. The domain is on our known piracy watchlist. Manual review suggested before action.',
  },
  {
    id: 'demo-alert-6',
    assetId: 'demo-asset-5',
    confidence: 0.44,
    foundUrl: 'https://sportsbay.org/tennis/wimbledon-photos',
    thumbnailUrl: null,
    severity: 'low',
    riskScore: 22,
    riskLabel: 'low',
    classification: 'review',
    isRead: true,
    createdAt: ts(6),
    smartSummary: 'Low-confidence match on sportsbay.org. A similar image to your Wimbledon photo was found but may be from a different angle or photographer. Confidence is 44%. Flagged for manual review — no automatic action taken.',
  },
];

export const DEMO_PROFILE = {
  accountType: 'organization',
  orgName: 'Premier Sports Media Ltd.',
  trustedDomains: ['espn.com', 'skysports.com', 'bbc.co.uk/sport', 'nba.com', 'premierleague.com', 'sportshield.app'],
  onboardingComplete: true,
};

export const DEMO_WATCHED_URLS = [
  {
    url: 'https://totalsportek.com/live-streams/',
    label: 'TotalSportek — top piracy aggregator',
    addedAt: ts(14),
    lastCheckedAt: ts(0.1),
    status: 'active',
    lastResult: { accessible: true, statusCode: 200, changed: true, checkedAt: ts(0.1) },
  },
  {
    url: 'https://sportsurge.io/premier-league',
    label: 'SportSurge — Premier League streams',
    addedAt: ts(7),
    lastCheckedAt: ts(0.1),
    status: 'active',
    lastResult: { accessible: true, statusCode: 200, changed: false, checkedAt: ts(0.1) },
  },
  {
    url: 'https://buffstreams.tv',
    label: 'BuffStreams — multi-sport piracy',
    addedAt: ts(10),
    lastCheckedAt: ts(0.1),
    status: 'active',
    lastResult: { accessible: true, statusCode: 200, changed: true, checkedAt: ts(0.1) },
  },
  {
    url: 'https://crackstreams-hd.eu',
    label: 'CrackStreams — taken down via ISP block',
    addedAt: ts(30),
    lastCheckedAt: ts(0.25),
    status: 'paused',
    lastResult: { accessible: false, statusCode: 451, changed: false, checkedAt: ts(0.25) },
  },
];

export const DEMO_REPORT = {
  id: 'demo-report-1',
  userId: 'demo_user',
  generatedAt: ts(0),
  periodStart: ts(7),
  periodEnd: ts(0),
  stats: {
    newMatches: 36,
    alertsTriggered: 18,
    dmcaActionsTaken: 11,
    assetsScanned: 5,
    protectionScoreCurrent: 87,
    protectionScorePrevious: 74,
  },
  topAlerts: [
    { assetName: 'wimbledon-final-match-point.jpg', foundUrl: 'totalsportek.com/wimbledon-final-stream', confidence: 0.96, severity: 'high' },
    { assetName: 'la-liga-el-clasico-broadcast.mp4', foundUrl: 'buffstreams.tv/la-liga-el-clasico-live', confidence: 0.92, severity: 'high' },
    { assetName: 'premier-league-arsenal-goal-highlights.mp4', foundUrl: 'sportsurge.io/premier-league-replay-arsenal', confidence: 0.89, severity: 'high' },
    { assetName: 'nba-finals-lebron-dunk.jpg', foundUrl: 'reddit.com/r/nbastreams', confidence: 0.71, severity: 'medium' },
    { assetName: 'premier-league-arsenal-goal-highlights.mp4', foundUrl: 'footybite.cc/arsenal-goals-free-download', confidence: 0.58, severity: 'medium' },
  ],
  narrative: `This week was our most active period yet. SportShield scanned 5 protected assets across 142 web sources and detected 36 new unauthorized matches, triggering 18 alerts. Of these, 3 were critical-severity detections on major piracy platforms.\n\nThe highest-priority finding was your Wimbledon match-point photo appearing on totalsportek.com with 96% confidence — a site serving over 5M monthly visitors. A DMCA notice was filed within 4 minutes of detection and the content was removed within 2 hours.\n\nYour El Clasico broadcast was found streaming live on buffstreams.tv (92% confidence). We escalated this to ISP-level blocking in coordination with La Liga's anti-piracy unit. The Arsenal highlights appeared on sportsurge.io (89% confidence) and footybite.cc (58% confidence) — both received automated DMCA notices.\n\nIn total, 11 DMCA takedown actions were completed this week with a 91% success rate. Your protection score jumped from 74 to 87, the highest it has been since monitoring began.\n\nRecommendation: Enable Live Radar for the upcoming Champions League semifinal to catch pirate streams within seconds of going live. Your Wimbledon photo continues to be a high-value target — consider enabling forensic watermarking to trace the leak source.`,
  emailSent: true,
  emailSentAt: ts(0),
};

/* ── War Room / Live Radar demo data ── */

export const DEMO_RADAR_STATS = {
  active_events: 4,
  total_suspects_analyzed: 163,
  pirate_streams_found: 34,
  total_detections: 52,
};

export const DEMO_RADAR_EVENTS = [
  {
    event_id: 'evt_demo_001',
    event_name: 'Manchester City vs Liverpool — Premier League GW37',
    teams: ['Manchester City', 'Liverpool'],
    broadcaster: 'Sky Sports',
    league: 'Premier League 2025-26',
    status: 'monitoring',
    suspect_count: 42,
    detection_count: 18,
    created_at: ts(0),
  },
  {
    event_id: 'evt_demo_002',
    event_name: 'Real Madrid vs Bayern Munich — UCL Semi-Final Leg 2',
    teams: ['Real Madrid', 'Bayern Munich'],
    broadcaster: 'BT Sport / DAZN',
    league: 'UEFA Champions League',
    status: 'monitoring',
    suspect_count: 38,
    detection_count: 14,
    created_at: ts(0.5),
  },
  {
    event_id: 'evt_demo_003',
    event_name: 'India vs England — ICC Champions Trophy Final',
    teams: ['India', 'England'],
    broadcaster: 'Star Sports / Willow TV',
    league: 'ICC Champions Trophy 2026',
    status: 'monitoring',
    suspect_count: 51,
    detection_count: 22,
    created_at: ts(1),
  },
  {
    event_id: 'evt_demo_004',
    event_name: 'LA Lakers vs Boston Celtics — NBA Finals Game 5',
    teams: ['LA Lakers', 'Boston Celtics'],
    broadcaster: 'ESPN / ABC',
    league: 'NBA Finals 2026',
    status: 'completed',
    suspect_count: 32,
    detection_count: 11,
    created_at: ts(3),
  },
];

export const DEMO_DETECTIONS = [
  { detection_id: 'det_001', event_name: 'Manchester City vs Liverpool — Premier League GW37', source_url: 'https://totalsportek.com/manchester-city-vs-liverpool-live/', composite_score: 0.97, confidence: 'HIGH', detected_at: ts(0) },
  { detection_id: 'det_002', event_name: 'Manchester City vs Liverpool — Premier League GW37', source_url: 'https://sportsurge.io/epl-mci-liv-stream', composite_score: 0.94, confidence: 'HIGH', detected_at: ts(0) },
  { detection_id: 'det_003', event_name: 'Real Madrid vs Bayern Munich — UCL Semi-Final Leg 2', source_url: 'https://buffstreams.tv/ucl-real-bayern-live', composite_score: 0.91, confidence: 'HIGH', detected_at: ts(0.5) },
  { detection_id: 'det_004', event_name: 'India vs England — ICC Champions Trophy Final', source_url: 'https://webcric.me/india-vs-england-live-free', composite_score: 0.93, confidence: 'HIGH', detected_at: ts(1) },
  { detection_id: 'det_005', event_name: 'India vs England — ICC Champions Trophy Final', source_url: 'https://smartcric.live/champions-trophy-final', composite_score: 0.88, confidence: 'HIGH', detected_at: ts(1) },
  { detection_id: 'det_006', event_name: 'Manchester City vs Liverpool — Premier League GW37', source_url: 'https://footybite.cc/city-liverpool-free-hd', composite_score: 0.72, confidence: 'MEDIUM', detected_at: ts(0) },
  { detection_id: 'det_007', event_name: 'LA Lakers vs Boston Celtics — NBA Finals Game 5', source_url: 'https://nbastreams.to/lakers-celtics-game5', composite_score: 0.86, confidence: 'HIGH', detected_at: ts(3) },
  { detection_id: 'det_008', event_name: 'Real Madrid vs Bayern Munich — UCL Semi-Final Leg 2', source_url: 'https://hesgoal.tv/champions-league-live', composite_score: 0.68, confidence: 'MEDIUM', detected_at: ts(0.5) },
];

export const DEMO_ENFORCEMENT_STATS = {
  total_cases: 34,
  active_cases: 11,
  resolved_cases: 23,
  under_30_min_rate: 89,
};

export const DEMO_CASES = [
  { case_id: 'case_001', event_name: 'Man City vs Liverpool — PL', platform: 'totalsportek.com', source_url: 'https://totalsportek.com/manchester-city-vs-liverpool-live/', status: 'resolved_content_removed', escalation_level: 0 },
  { case_id: 'case_002', event_name: 'Man City vs Liverpool — PL', platform: 'sportsurge.io', source_url: 'https://sportsurge.io/epl-mci-liv-stream', status: 'dmca_filed', escalation_level: 1 },
  { case_id: 'case_003', event_name: 'Real Madrid vs Bayern — UCL', platform: 'buffstreams.tv', source_url: 'https://buffstreams.tv/ucl-real-bayern-live', status: 'escalated_isp', escalation_level: 2 },
  { case_id: 'case_004', event_name: 'India vs England — CT Final', platform: 'webcric.me', source_url: 'https://webcric.me/india-vs-england-live-free', status: 'dmca_filed', escalation_level: 0 },
  { case_id: 'case_005', event_name: 'India vs England — CT Final', platform: 'smartcric.live', source_url: 'https://smartcric.live/champions-trophy-final', status: 'resolved_content_removed', escalation_level: 0 },
  { case_id: 'case_006', event_name: 'Lakers vs Celtics — NBA F G5', platform: 'nbastreams.to', source_url: 'https://nbastreams.to/lakers-celtics-game5', status: 'dmca_generated', escalation_level: 0 },
  { case_id: 'case_007', event_name: 'Man City vs Liverpool — PL', platform: 'footybite.cc', source_url: 'https://footybite.cc/city-liverpool-free-hd', status: 'escalated_isp', escalation_level: 2 },
  { case_id: 'case_008', event_name: 'Real Madrid vs Bayern — UCL', platform: 'hesgoal.tv', source_url: 'https://hesgoal.tv/champions-league-live', status: 'dmca_filed', escalation_level: 1 },
];

export const DEMO_CROWD_STATS = {
  total_contributors: 1247,
  total_submissions: 4891,
  verified_pirates: 1836,
  verification_rate: 38,
};

export const DEMO_LEADERBOARD = [
  { user_id: 'u1', display_name: 'PiracyHunter_IN', rank: 'legend', total_points: 14820, verified_finds: 187 },
  { user_id: 'u2', display_name: 'StreamWatch_UK', rank: 'legend', total_points: 12350, verified_finds: 154 },
  { user_id: 'u3', display_name: 'EPL_Guardian', rank: 'expert', total_points: 8740, verified_finds: 98 },
  { user_id: 'u4', display_name: 'CricketShield', rank: 'expert', total_points: 6890, verified_finds: 72 },
  { user_id: 'u5', display_name: 'LaLigaPatrol', rank: 'veteran', total_points: 4420, verified_finds: 51 },
  { user_id: 'u6', display_name: 'NBAWatchdog', rank: 'veteran', total_points: 3960, verified_finds: 44 },
  { user_id: 'u7', display_name: 'AntiPirate_SA', rank: 'hunter', total_points: 2710, verified_finds: 28 },
  { user_id: 'u8', display_name: 'F1StreamGuard', rank: 'hunter', total_points: 1840, verified_finds: 19 },
  { user_id: 'u9', display_name: 'SerieADefender', rank: 'scout', total_points: 920, verified_finds: 11 },
  { user_id: 'u10', display_name: 'UFC_Sentinel', rank: 'scout', total_points: 540, verified_finds: 6 },
];
